booking/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'booking'

urlpatterns = [
    path('users/', include('users.urls')),
    path('users/profile/<int:pk>/booking/', views.BookingView.as_view(), name='user_booking_new'),
    path('users/profile/<int:pk>/booking/group/', views.GroupView.as_view(), name='user_group_booking_new'),
    path('booking/', views.BookingListView.as_view(), name="booking_list"),
    path('tutorials/', views.TutorialListView.as_view(), name="tutorial_list"),
    path('booking/<int:pk>/', views.BookingDetailView.as_view(), name="booking_detail"),
    path('booking/edit/<int:pk>/', views.BookingUpdateView.as_view(), name="booking_update"),
    path('booking/delete/<int:pk>/', views.BookingDeleteView.as_view(), name="booking_delete"),
    path('booking/confirm/<int:pk>/', views.ConfirmView.as_view(), name='confirm_booking'),
    path('booking/request_expert/', views.RequestExpertView.as_view(), name='request_expert'),
    path('help_needed/', views.RequestExpertView.as_view(), name='help_form'),
#    path('users/profile/<int:pk>/booking/<int:pk>/', views.BookingDetailView.as_view(), name="booking_detail"),
#    path('users/profile/<int:pk>/booking/edit/<int:pk>/', views.BookingUpdateView.as_view(), name="booking_update"),
#    path('booking/edit/<int:pk>/booking/delete/<int:pk>/', views.BookingDeleteView.as_view(), name="booking_delete"),
 
 
]



    #path('users/profile/booking/', views.CalendarView.as_view(), name='calendar'),
    #path('booking/calendar/', views.calendar, name='new_calendar'),

pages/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('faq/', views.FAQView.as_view(), name='faq'),
   
]

scipertise_demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404


urlpatterns = [
 
    path('superusers/access/admin/scipertise/', admin.site.urls),
    path('', include('pages.urls')),
    path('search/', include('search.urls', namespace='search')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', include('booking.urls', namespace='booking')),
    path('chat/', include('chatapp.urls')),
    path('accounts/', include('allauth.urls')), 
    

  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.error_404_view'

booking/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.urls import reverse
from users.models import CustomUser

 

# Create your models here.

class Booking(models.Model):
    user = models.ForeignKey(CustomUser, null=True, default='', on_delete=models.CASCADE)
    expert = models.ForeignKey(CustomUser, null=True, default='',on_delete=models.CASCADE, related_name='bookings')
    title = models.CharField(max_length=200, default='e.g. Advice on statistics', null=True)
    start_time = models.DateTimeField('Start time', null=True)
    end_time = models.DateTimeField('End time', null=True)
    notes = models.TextField('Notes', blank=True, null=True) 
    is_confirmed = models.BooleanField(blank=True, default=False)
    is_tutorial = models.BooleanField(blank=True, default=False)
    description = models.TextField('Description', blank=True, null=True) 
  
 
    class Meta:
        verbose_name = 'Booking'
        verbose_name_plural = 'Bookings'
        
    def get_absolute_url(self):
        return reverse('booking:booking_detail', kwargs={"pk": self.pk})
    
#class Confirmation(models.Model):
#    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
#    expert_confirming = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
#    is_confirmed = models.BooleanField(default=False)
#    
#    def get_absolute_url(self):
#        return reverse('booking:booking_detail', kwargs={"pk": self.booking_id})
#    

class HelpRequest(models.Model):
    user = models.ForeignKey(CustomUser, null=True, default='', on_delete=models.CASCADE)
    help_needed = models.TextField(blank=True, null=True) 
    
    class Meta:
        verbose_name = 'HelpRequest'
        verbose_name_plural = 'HelpRequests'
        
    def get_absolute_url(self):
        return reverse('booking:request_expert')
        

    

booking/forms.py
from django.forms import ModelForm, DateInput
from booking.models import Booking, HelpRequest
from django import forms
from bootstrap_datepicker_plus import DatePickerInput, TimePickerInput, DateTimePickerInput, MonthPickerInput, YearPickerInput


        
class BookingForm(ModelForm):
    class Meta:
        model = Booking
        fields = ['title','start_time','end_time','notes']
        # datetime-local is a HTML5 input type, format to make date time show on fields
        labels = {
          'title': 'Please enter a title for your call',
          'start_time': 'Suggested date and start time',
          'end_time': 'Suggested end time',
          'notes': "Briefly describe what you are interested in discussing or what you need guidance on. If you’d like this session to be a tutorial on a specific topic, refer to the expert’s available tutorial topics under ‘Tutorials’ on their expert profile page.",
        }
        widgets = {
          'title': forms.TextInput(attrs={'class': 'form-control'}),
          'start_time': DateTimePickerInput(format="YYYY-MM-DD HH:mm"),
          'end_time': DateTimePickerInput(format="YYYY-MM-DD HH:mm"),
          'notes': forms.Textarea(attrs={'class': 'form-control'}),
        }
        help_texts = {
    
          'start_time': 'Please select a date and time during the available hours listed at the top of this form',
          'end_time': '*Appointments cannot exceed 1 hour',
          
        }
        
class GroupForm(ModelForm):
    class Meta:
        model = Booking
        fields = ['title','start_time','end_time','notes']
        # datetime-local is a HTML5 input type, format to make date time show on fields
        labels = {
          'title': 'Please enter a title for the group session',
          'start_time': 'Suggested date and start time',
          'end_time': 'Suggested end time',
          'notes': "Briefly describe what you are interested in discussing in this group session, referring to the expert's available tutorial topics under 'Tutorials' on their profile page.",
        }
        widgets = {
          'title': forms.TextInput(attrs={'class': 'form-control'}),
          'start_time': DateTimePickerInput(format="YYYY-MM-DD HH:mm"),
          'end_time': DateTimePickerInput(format="YYYY-MM-DD HH:mm"),
          'notes': forms.Textarea(attrs={'class': 'form-control'}),
        }
        help_texts = {
    
          'start_time': 'Please select a date and time during the available hours listed at the top of this form',
          'end_time': '*Group sessions cannot exceed 1 hour',
          
        }



class ConfirmForm(ModelForm):
    class Meta:
        model = Booking
        fields = ['is_confirmed']
        # datetime-local is a HTML5 input type, format to make date time show on fields
        labels = {
          'is_confirmed': 'I confirm this video call',
        }
        
class RequestExpertForm(forms.ModelForm):
   
    
    class Meta:
        model = HelpRequest
        fields =('help_needed',)
        labels = {
            'help_needed': 'Please provide a brief description of what you need help with or would like to learn below.'
        }
        widgets = {
            'help_needed': forms.Textarea(attrs={'class': 'form-control'}),
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['help_needed'].widget.attrs['class'] = 'form-control'
  
       
        

booking/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.views.generic import CreateView, TemplateView, DetailView, ListView, UpdateView, DeleteView
from django.http import HttpResponseRedirect
from datetime import datetime
from django.http import HttpResponse
from django.utils.safestring import mark_safe
from datetime import datetime, timedelta
from calendar import HTMLCalendar
import calendar
from django.core.mail import send_mail, mail_admins
from django.contrib.auth.decorators import login_required

from users.forms import CustomUserCreationForm, EditProfile
from users.models import CustomUser
#from booking.utils import Calendar
from booking.models import Booking, HelpRequest
from booking.forms import BookingForm, ConfirmForm, GroupForm, RequestExpertForm

from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.contrib.messages.views import SuccessMessageMixin


class BookingView(CreateView):
    model = Booking
    form_class = BookingForm
    def form_valid(self, form):
        booking = form.save(commit=False)
        form.instance.user = self.request.user
        form.instance.expert = CustomUser.objects.get(id=self.kwargs.get('pk'))
        user_email = form.instance.user.email
        expert_email = form.instance.expert.email

        html_message = render_to_string('booking_request_email_user.html', {'user': form.instance.user,
                                                                            'expert': form.instance.expert})
        html_message_expert = render_to_string('booking_request_email_expert.html', {'user': form.instance.user,
                                                                            'expert': form.instance.expert,
                                                                            'booking': booking,
                                                                            })
        plain_message = strip_tags(html_message)
        plain_message_expert = strip_tags(html_message_expert)
    #send email to the user
        send_mail('Thanks for your booking request ' + form.instance.user.first_name, plain_message, 'founders@scipertise.com', [user_email], fail_silently=False, html_message=html_message)
    #send email to the expert
        send_mail(form.instance.user.first_name + " has requested a video call with you", plain_message_expert, 'founders@scipertise.com', [expert_email], fail_silently=False, html_message=html_message_expert)
    #send email to scipertise admin
        mail_admins('New booking request made', 'A new booking request has been made by' + form.instance.user.first_name, fail_silently=False, )
        return super(BookingView, self).form_valid(form)
        

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['expert'] = CustomUser.objects.get(id=self.kwargs.get('pk'))
        return context
    

class GroupView(CreateView):
    model = Booking
    form_class = GroupForm
    template_name = 'booking/group_form.html'
    def form_valid(self, form):
        booking = form.save(commit=False)
        form.instance.user = self.request.user
        form.instance.expert = CustomUser.objects.get(id=self.kwargs.get('pk'))
        form.instance.is_tutorial = True
        user_email = form.instance.user.email
        expert_email = form.instance.expert.email

        html_message = render_to_string('booking_request_email_user.html', {'user': form.instance.user,
                                                                            'expert': form.instance.expert})
        html_message_expert = render_to_string('booking_request_email_expert.html', {'user': form.instance.user,
                                                                            'expert': form.instance.expert,
                                                                            'booking': booking,
                                                                            })
        plain_message = strip_tags(html_message)
        plain_message_expert = strip_tags(html_message_expert)
    #send email to the user
        send_mail('Thanks for your booking request ' + form.instance.user.first_name, plain_message, 'founders@scipertise.com', [user_email], fail_silently=False, html_message=html_message)
    #send email to the expert
        send_mail(form.instance.user.first_name + " has requested a video call with you", plain_message_expert, 'founders@scipertise.com', [expert_email], fail_silently=False, html_message=html_message_expert)
#    #send email to scipertise admin
        mail_admins('New group booking request made', 'A new booking request has been made by' + form.instance.user.first_name, fail_silently=False, )
        return super(GroupView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['expert'] = CustomUser.objects.get(id=self.kwargs.get('pk'))
        return context

    
class BookingUpdateView(UpdateView):
    model = Booking
    form_class = BookingForm
    def form_valid(self, form):
        booking = Booking.objects.get(id=self.kwargs.get('pk'))
        form.instance.user = booking.user
        form.instance.expert = booking.expert
        user_email = form.instance.user.email
        expert_email = form.instance.expert.email
        html_message = render_to_string('update_booking_user.html', {'user': form.instance.user,
                                                                            'expert': form.instance.expert,
                                                                            'booking': booking,
                                                                            })
        html_message_expert = render_to_string('update_booking_expert.html', {'user': form.instance.user,
                                                                            'expert': form.instance.expert,
                                                                            'booking': booking,
                                                                            })
        plain_message = strip_tags(html_message)
        plain_message_expert = strip_tags(html_message_expert)
    #send email to the user
        send_mail('Your Scipertise booking request has been changed', plain_message, 'founders@scipertise.com', [user_email], fail_silently=False, html_message=html_message)
    #send email to the expert
        send_mail('Your Scipertise booking request has been changed', plain_message_expert, 'founders@scipertise.com', [expert_email], fail_silently=False, html_message=html_message_expert)
#    #send email to scipertise admin
        mail_admins('Change to booking request made', 'A change to booking request has been made for' + booking.title, fail_silently=False, )
        return super(BookingUpdateView, self).form_valid(form)

    
class BookingDeleteView(DeleteView):
    model = Booking
    success_url = reverse_lazy('profile')
    def form_valid(self, form):
        booking = Booking.objects.get(id=self.kwargs.get('pk'))
        form.instance.user = booking.user
        form.instance.expert = booking.expert
        user_email = form.instance.user.email
        expert_email = form.instance.expert.email
        html_message = render_to_string('delete_booking_user.html', {'user': form.instance.user,
                                                                            'expert': form.instance.expert,
                                                                            'booking': booking,
                                                                            })
        html_message_expert = render_to_string('delete_booking_expert.html', {'user': form.instance.user,
                                                                            'expert': form.instance.expert,
                                                                            'booking': booking,
                                                                            })
        plain_message = strip_tags(html_message)
        plain_message_expert = strip_tags(html_message_expert)
    #send email to the user
        send_mail('Your Scipertise booking has been cancelled', plain_message, 'founders@scipertise.com', [user_email], fail_silently=False, html_message=html_message)
    #send email to the expert
        send_mail('Your Scipertise booking has been cancelled', plain_message_expert, 'founders@scipertise.com', [expert_email], fail_silently=False, html_message=html_message_expert)
#    #send email to scipertise admin
        mail_admins('Booking request deleted', 'A booking request has been deleted:' + booking.title, fail_silently=False, )
        return super(BookingDeleteView, self).form_valid(form)

class BookingListView(ListView):
    model = Booking
    context_object_name = 'booking_list'
  
    
    def get_queryset(self):
        bookings = Booking.objects.filter(user=self.request.user)
        return bookings
    
class TutorialListView(ListView):
    model = Booking
    context_object_name = 'tutorial_list'
    template_name = 'booking/tutorial_list.html'
    
    def get_queryset(self):
        tutorials = Booking.objects.filter(is_tutorial=True)
        return tutorials

    
class BookingDetailView(DetailView):
    model = Booking
    template = 'templates/booking_detail.html'
    
class ConfirmView(UpdateView):
    model = Booking
    form_class = ConfirmForm
    template = 'templates/confirmation_form.html'
    def form_valid(self, form):
        booking = Booking.objects.get(id=self.kwargs.get('pk'))
        form.instance.user = booking.user
        form.instance.expert = booking.expert
        user_email = form.instance.user.email
        expert_email = form.instance.expert.email

booking/templates/booking/booking_confirm_delete.html
{% extends 'layout.html' %}
{% load static %}

<h1>Bookings</h1>

{% block content %}
<div class="container-fluid booking">
<div class="container">
<h3 class='confirm_delete_title'>Delete {{ booking.title }}?</h3>
<div class="container delete_booking">
    <form  method ="POST">
    {% csrf_token %}
   <button type='submit' class='btn btn-danger' value="Delete">Delete Booking</button>
    </form> 
    <a href="{% url 'booking:booking_list' %}" class="cancel_link">Cancel</a>
    </div>


</div>
    </div>

{% endblock %}

booking/templates/booking/booking_detail.html
{% extends 'layout.html' %}
{% load static %}

<h1>Bookings</h1>

{% block content %}

<div class="container-fluid booking">
    
  
    <div class="container" id="booking_content">
        <div class="container card">
            <div class="container text_container_card">
        {% if booking.is_tutorial %}
<h3 class="booking_form_text">Group Video Tutorial Details</h3><br>
        {% else %}
   <h3 class="booking_form_text">Booking details</h3>
            {% endif %}
            
        <div class="container"><h4 class="tutorial_title">{{ booking.title }}&nbsp&nbsp</h4></div>
     {% if booking.is_tutorial %}
          <div class="container confirmed">
        {% if booking.is_confirmed %}
      <p class="confirmed">This tutorial is confirmed.&nbsp&nbsp</p><img class="check" src="/static/css/check.svg">
        {% else %}
        <p class="confirmed">This tutorial has not yet been confirmed by the requested expert. You will receive an email upon confirmation.&nbsp&nbsp<img class="x" src="/static/css/warning.svg"></p>
        {% endif %}
            
            </div>
            {% else %}
            
    <div class="container confirmed">
        {% if booking.is_confirmed %}
      <p class="confirmed">This booking is confirmed.&nbsp&nbsp</p><img class="check" src="/static/css/check.svg">
        {% else %}
        <p class="confirmed">This booking has not yet been confirmed by the requested expert. You will receive an email upon confirmation.&nbsp&nbsp<img class="x" src="/static/css/warning.svg"></p>
        {% endif %}
            
            </div>  
            {% endif %}
            
            
        <div class="container">
        <p><strong>Date:</strong> {{ booking.start_time }} EST</p>
<!--        <p>Booking made by: {{ booking.user }}</p>-->
        {% if booking.is_tutorial %}
        <p><strong>Tutorial hosted by:</strong> {{ booking.expert.first_name }}&nbsp{{ booking.expert.last_name }}</p>
            {% else %}
        <p>Scipertise expert/mentor: {{ booking.expert.first_name }}&nbsp{{ booking.expert.last_name }}</p>
            {% endif %}
        {% if booking.is_tutorial %}
            <h4 class="text_title">{{ booking.description }}</h4><br>
 <!-- ADD SPECIFIC DEETS FOR MAC TUTORIAL -->   
                {% if booking.title == 'Imaging the Dynamic Core of the Human Brain' %}
            <h4 class="bio_title"><strong>About the Tutorial</strong></h4>
           <p class="profile_text">The goal of this Scipertise tutorial is to provide participants with a better understanding of the methodologies used in the Shine, Breakspear et al. Nature Neuroscience paper by providing a walk through of the methods applied. Participants will feel more comfortable applying these analytical techniques to their own fMRI or other neuroimaging data. Attendance is limited in order to allow for an interactive experience for participants. There will be some time for questions throughout the tutorial.</p> <br>

                 <h4 class="bio_title"><strong>Topics Covered</strong></h4> 
            <p>Introduction to paper, spatiotemporal principal components analysis (PCA) methodology, manifold/embedding space, use of NeuroSynth, time-varying connectivity, graph theory/topology, Allen Brain Atlas. </p>

            <p class="profile_text"><a href="https://www.nature.com/articles/s41593-018-0312-0">Shine, Breakspear et al.</a> Human cognition involves the dynamic integration of neural activity and neuromodulatory systems. Nature Neuroscience (2019).</p><br>

<p>Attendees are invited to see Dr. Shine's <a href="https://github.com/macshine/state_space/">GitHub repository </a>for this paper in advance of the tutorial.</p>
            {% endif %}
 <!-- END ADD SPECIFIC DEETS FOR MAC TUTORIAL -->   
            
            
        {% endif %}  
            {% if not booking.is_confirmed and user.expert and booking.expert == request.user %}
            <div><a href="{% url 'booking:confirm_booking' pk=booking.pk %}"><button type='submit' class='booking_button'>Confirm Booking Request</button></a></div> 
            {% endif %}
            {% if booking.user == request.user or booking.expert == request.user %}
            <div><a href="{% url 'booking:booking_update' pk=booking.pk %}"><button type='submit' class='booking_button'>Edit Booking</button></a></div> 
            <div><a href="{% url 'booking:booking_delete' pk=booking.pk %}"><button type='submit' class='booking_button'>Delete Booking</button></a></div>   
            {% endif %}
<!-- ADD SPECIFIC DEETS FOR MAC TUTORIAL -->   
                {% if booking.title == 'Imaging the Dynamic Core of the Human Brain' %}
                     <div class="eventbrite_button">
                    <!-- Noscript content for added SEO -->
        <noscript><a href="https://www.eventbrite.ca/e/imaging-the-dynamic-core-of-the-brain-tutorial-by-mac-shine-tickets-56310316673" rel="noopener noreferrer" target="_blank"></noscript>
        <!-- You can customize this button any way you like -->
        <button class="booking_button eventbrite" id="eventbrite-widget-modal-trigger-56310316673" type="button">Reserve a Spot</button>
        <noscript></a>Buy Tickets on Eventbrite</noscript>

        <script src="https://www.eventbrite.ca/static/widgets/eb_widgets.js"></script>

        <script type="text/javascript">
            var exampleCallback = function() {
                console.log('Order complete!');
            };

            window.EBWidgets.createWidget({
                widgetType: 'checkout',
                eventId: '56310316673',
                modal: true,
                modalTriggerElementId: 'eventbrite-widget-modal-trigger-56310316673',
                onOrderComplete: exampleCallback
            });
        </script>
                </div>

                    {% endif %}
<!-- END ADD SPECIFIC DEETS FOR MAC TUTORIAL -->  
    </div>

    </div>
    </div>


    </div>
  
</div>



{% endblock %}

booking/templates/booking/booking_form.html
{% extends 'layout.html' %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }} 
{% load widget_tweaks %}

{% block title %}
Event
{% endblock %}

{% block content %}

<div class="container-fluid booking">
   
<div class="container" id="booking_form">
    
     {% if booking and booking.is_confirmed == False and booking.user == request.user %}
    <div class="container" id="booking_form_text"><h3 class="booking_form_text">Please select a new time for your video call</h3></div>
    {% elif booking and booking.is_confirmed == False and booking.expert == request.user %}
     <div class="container" id="booking_form_text"><h3 class="booking_form_text">Please confirm booking request</h3></div>
    {% elif booking %}
    <div class="container" id="booking_form_text"><h3 class="booking_form_text">Please select a new time for your video call</h3></div>
    {% else %}
    <div class="container" id="booking_form_text"><h3 class="booking_form_text">Request a video call</h3></div>
     {% endif %}
   
    <form method="post">
      {% csrf_token %}
       
    <div class="form-group booking_form">
<!--    <h4 class="bio_title">*{{ expert.first_name }}'s availability is: {{ expert.availability }} </h4>-->
     {% for field in form.visible_fields %}
      
      {{ field.label_tag }}
      {% render_field field class="form-control" %}
      {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text |safe }}</small>
      {% endif %}
    {% endfor %}
    <button type="submit" class="availability_button">Submit</button><br><br>
    
  </div>
</form>
        
        
        
        
        
<!--
        
    <form method="post" class="booking_form">
      {% csrf_token %}

        {{ form.as_p }}

    <button type="submit" class="availability_button"> Request to Book </button>

    </form>
-->
    </div>
</div>


{% endblock %}

booking/templates/booking/booking_list.html
{% extends 'layout.html' %}
{% load static %}


{% block content %}
<div class="container-fluid booking">



<div class='container booking_list'>
{% if user.bookings.all or user.booking_set.all %}
<div class="container" id="booking_form_text"><h3 class="video_sessions">Your scheduled video sessions:</h3></div>
   
{% for booking in user.bookings.all %}
    
    <div class="container card booking_list">
        <h5 class="card-title"><a href="{% url 'booking:booking_detail' pk=booking.pk %}">{{ booking.title }}</a></h5>
        <p class="card-text">Date: {{booking.start_time}}</p>
    </div>
    
{% endfor %}
{% for booking in user.booking_set.all %}
    
       <div class="container card booking_list">
        <h5 class="card-title"><a href="{% url 'booking:booking_detail' pk=booking.pk %}">{{ booking.title }}</a></h5>
        <p class="card-text">Date: {{booking.start_time}}</p>
    </div>
{% endfor %}
    
</div>


{% else %} 

<div class="container" id="booking_form_text"><h3 class="video_sessions">You have no scheduled video sessions.</h3></div>
   

{% endif %}
    </div>




{% endblock %}

booking/templates/booking/confirmation_form.html
{% extends 'layout.html' %}
{% load static %}
{% load widget_tweaks %}

<h1>Bookings</h1>

{% block content %}

<div class="container-fluid booking">
    <div class="container" id="booking_form_text"><h3>Booking request confirmation</h3></div>
    <div class="container" id="booking_content">
        
    <form method="post">
      {% csrf_token %}

    <div class="form-group booking_form">
     {% for field in form.visible_fields %}
      {{ field.label_tag }}
      {% render_field field class="form-control" %}<br>
      {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text |safe }}</small>
      {% endif %}
    {% endfor %}
    <button type="submit" class="availability_button">Yes I Confirm</button>
    </div>
  
</form>
    </div>

</div>



{% endblock %}

booking/templates/booking/group_form.html
{% extends 'layout.html' %}
{% load static %}
{% load bootstrap4 %}       {# imports bootstrap3 #}
{% bootstrap_css %}         {# Embeds Bootstrap CSS #}
{% bootstrap_javascript %}
{% bootstrap_javascript jquery='full' %} {# Embeds Bootstrap JS #}
{% block extrahead %} 
 {{ form.media }}          {# Embeds Extra Resources #}
{% endblock %}              {# Ends Extra Resources #}
{% load widget_tweaks %}

{% block title %}
Event
{% endblock %}

{% block content %}

<div class="container-fluid booking">
 
<div class="container" id="booking_form">
    
       {% if booking and booking.is_confirmed == False and booking.user == request.user %}
    <div class="container" id="booking_form_text"><h3 class="booking_form_text">Please select a new time for your group session</h3></div>
    {% elif booking and booking.is_confirmed == False and booking.expert == request.user %}
     <div class="container" id="booking_form_text"><h3 class= "booking_form_text">Please confirm group session</h3></div>
    {% elif booking %}
    <div class="container" id="booking_form_text"><h3  class= "booking_form_text">Please select a new time for your group session</h3></div>
    {% else %}
    <div class="container" id="booking_form_text"><h3  class= "booking_form_text">Request a group video session</h3></div>
     {% endif %}
   
    <form method="post">
      {% csrf_token %}
       
    <div class="form-group booking_form">
    <h4 class="bio_title">*{{ expert.first_name }}'s availability is: {{ expert.availability }} </h4>
    <p>When you request a group session, up to 3 other people can sign up. The cost of the session is shared amongst participants. At least one other person must sign up 24 hours prior to the session's start time. If not, the session will be cancelled, and you are welcome to book an individual session instead.</p>
     {% for field in form.visible_fields %}
      
      {{ field.label_tag }}
      {% render_field field class="form-control" %}
      {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text |safe }}</small>
      {% endif %}
    {% endfor %}
    <button type="submit" class="availability_button">Submit</button><br><br>
    
  </div>
</form>
        
        
        
        
        
<!--
        
    <form method="post" class="booking_form">
      {% csrf_token %}

        {{ form.as_p }}

    <button type="submit" class="availability_button"> Request to Book </button>

    </form>
-->
    </div>
</div>


{% endblock %}