booking/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'booking'

urlpatterns = [
    path('users/', include('users.urls')),
    path('users/profile/<int:pk>/booking/', views.BookingView.as_view(), name='user_booking_new'),
    path('users/profile/<int:pk>/booking/group/', views.GroupView.as_view(), name='user_group_booking_new'),
    path('booking/', views.BookingListView.as_view(), name="booking_list"),
    path('tutorials/', views.TutorialListView.as_view(), name="tutorial_list"),
    path('booking/<int:pk>/', views.BookingDetailView.as_view(), name="booking_detail"),
    path('booking/edit/<int:pk>/', views.BookingUpdateView.as_view(), name="booking_update"),
    path('booking/delete/<int:pk>/', views.BookingDeleteView.as_view(), name="booking_delete"),
    path('booking/confirm/<int:pk>/', views.ConfirmView.as_view(), name='confirm_booking'),
    path('booking/request_expert/', views.RequestExpertView.as_view(), name='request_expert'),
    path('help_needed/', views.RequestExpertView.as_view(), name='help_form'),
#    path('users/profile/<int:pk>/booking/<int:pk>/', views.BookingDetailView.as_view(), name="booking_detail"),
#    path('users/profile/<int:pk>/booking/edit/<int:pk>/', views.BookingUpdateView.as_view(), name="booking_update"),
#    path('booking/edit/<int:pk>/booking/delete/<int:pk>/', views.BookingDeleteView.as_view(), name="booking_delete"),
 
 
]



    #path('users/profile/booking/', views.CalendarView.as_view(), name='calendar'),
    #path('booking/calendar/', views.calendar, name='new_calendar'),

pages/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('faq/', views.FAQView.as_view(), name='faq'),
   
]

scipertise_demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404


urlpatterns = [
 
    path('superusers/access/admin/scipertise/', admin.site.urls),
    path('', include('pages.urls')),
    path('search/', include('search.urls', namespace='search')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', include('booking.urls', namespace='booking')),
    path('chat/', include('chatapp.urls')),
    path('accounts/', include('allauth.urls')), 
    

  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.error_404_view'

search/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import search_users


app_name = 'search'

urlpatterns = [
    path('', search_users, name='search_users'),
    path('users/', include('users.urls')),

   
 
] 

search/views.py
from django.shortcuts import render
from django.db.models import Q
from users.models import CustomUser
from django.views.generic import TemplateView, DetailView, ListView
from users.models import CustomUser
from taggit.models import Tag
from functools import reduce

# Create your views here.

def search_users(request):
    if request.method == 'GET':
        query= request.GET.get('q')
        submitbutton= request.GET.get('submit')
        if query is not None:
            lookups = Q(skills__name__icontains=query) | Q(software_hardware__icontains=query) |  Q(software_hardware_intermediate__icontains=query)
            results = CustomUser.objects.filter(lookups).distinct()
            context={'results': results, 'submitbutton': submitbutton}
            return render(request, 'search.html', context)
        else:
            return render(request, 'search.html')
    else:
        return render(request, 'search.html')



 

templates/booking_request_email_expert.html
<h4>Hi {{ expert.first_name }}, </h4>

<p>{{ user.first_name }} has requested a video call with you for {{ booking.start_time }} The title of the booking is {{ booking.title }}.<br>Here is a short description of what they would like to discuss: {{ booking.notes }}<br> Please login <a href="www.scipertise.com">here</a>, select "My Schedule" and click on the booking to confirm.</p>
<p>Sincerely,</p>
<p>The Scipertise Team</p>

templates/change_password.html
{% extends 'layout.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %}Change Password{% endblock %}

{% block content %}

<div class="container-fluid" id="change_password">

<div class="container" id="edit_profile">

<!--
<form class="signup_form" action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
     <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
-->
    
    
<form method="post">
      {% csrf_token %}

    <div class="form-group">
     {% for field in form.visible_fields %}
     {{ field.errors }}
      {{ field.label_tag }}
      {% render_field field class="form-control" %}
      {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text |safe }}</small>
      {% endif %}
    {% endfor %}
    </div>
  <button type="submit" class="availability_button">Save Changes</button>
</form>
               
</div>
    </div>


{% endblock %}
        

templates/confirm_booking_expert.html
<h4>Hi {{ expert.first_name }}, </h4>

<p>Thanks for confirming your booking with {{ user.first_name }} for {{ booking.start_time }}<br> 
You will receive a reminder email and link to the video conference prior to your call.</p>
<p>Sincerely,</p>
<p>The Scipertise Team</p>

templates/custom_404.html
{% load static %}

<html>
<head>
     <link rel="stylesheet" href="{% static '/css/layout.css' %}">
  
    <link href="https://fonts.googleapis.com/css?family=Montserrat|PT+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet"> 
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="iconic.min.js"></script>
    </head>
<div class="container jumbotron">
    	<h1>oops!</h1>
			<h2>Error 404 : Page Not Found</h2>
			<a href="{% url 'home' %}">Go back to the homepage</a>
    </div>
</html>

templates/delete_booking_user.html
<h4>Hi {{ user.first_name }}, </h4>

<p>Your video call titled {{ booking.title }}, with {{ expert.first_name }} has been cancelled. Thank you for using Scipertise.</p>
<p>Sincerely,</p>
<p>The Scipertise Team</p>

templates/edit_profile_image.html
{% extends 'layout.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Edit Profile Image{% endblock %}

{% block content %}


<div class="container-fluid booking"> 
<div class="container profile_image_page">
<form method="post" enctype="multipart/form-data" class="edit_profile_image">
    {% csrf_token %}
    {{ form.as_p }}
    
     <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
    </div>
    
    
</div>

{% endblock %}

templates/edit_profile_rate.html
{% extends 'layout.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Edit Rate and Availability{% endblock %}

{% block content %}


<div class="container-fluid booking">


    
<form  class="form-group booking_form"  method="post">
      {% csrf_token %}
    <div class="container" id="booking_form">

    <h3 class="edit_profile_subheading">Rates and Availability</h3>
        {{ form_two.rate.label_tag }}
          {% render_field form_two.rate class="form-control" %}
          {% if form_two.rate.help_text %}
        <small class="form-text text-muted">{{ form_two.rate.help_text |safe }}</small>
          {% endif %}
        {{ form_two.availability.label_tag }}
          {% render_field form_two.availability class="form-control" %}
          {% if form_two.availability.help_text %}
        <small class="form-text text-muted">{{ form_two.availability.help_text |safe }}</small>
          {% endif %}
     <button type="submit" class="btn btn-primary edit_profile">Save</button>
    </div>
     </form>
   
    
    

    

        
    </div>     
               




{% endblock %}

templates/faq.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}

<div class="container-fluid" id="profile_container">
   
<div class="container profile">
  
     <div class="container" id="profile_content">
         <div class="profile_content_text">
         <h3 class="booking_form_text">FAQ</h3><br>
             <i><strong>What is Scipertise?</strong></i>
<p class="profile_text">Scipertise is a platform for finding live research help or advice via video chat. Scipertise helps you connect with a researcher who has the right expertise you need to solve your problems and do better research. <a href="{% url 'signup' %}">Sign up</a> to request a video session with an expert, <a href="{% url 'booking:request_expert' %}">submit a request</a> for expertise or <a href="{% url 'signup' %}">apply</a> to become an expert by submitting a profile.</p>
        <div class="divider"></div>
             <i><strong>How do I book a video chat?</strong></i>
                 

             <p class="profile_text">When viewing an expert’s profile, click ‘Request to Book’ to create a request with a suggested time to video chat and the topic or questions you’d like to discuss. If the expert lists any topics they can give a tutorial on in their ‘Tutorials’ section, you can also request a specific tutorial -make this clear in the notes. The expert’s hourly rate tells you how much the video chat will cost. You will only be charged for the length of the call. </p>
                 
    <div class="divider"></div>
<i><strong>How do group sessions work?</strong></i>
             <p class="profile_text">In group sessions, experts lead a tutorial for 2-5 people. If the expert you’d like to chat with offers group sessions, you can click ‘Join a group session’ to join an existing group tutorial session or ‘Request a new group session’ to create a new video session that others can join. At least 2 participants must join for the session to be confirmed.</p>
                 
    <div class="divider"></div>
<i><strong>How do I become an expert?</strong></i>
<p class="profile_text">Principal investigators, post-doctoral fellows, PhD students, and other researchers who have expertise in the life sciences or related fields can apply to be an expert by filling out and submitting an expert profile for review. Ensure that you add your title, a short bio, skill tags and at least one skill area to your profile prior to submission. Submitted profiles will be reviewed for accuracy, completeness, and an initial decision will be made within 48 hours.</p>
                 
    <div class="divider"></div>
<i><strong>What commitment is required as an expert?</strong></i> 
             <p class="profile_text">Experts are asked to respond to requests to video chats in a timely manner. If you do not feel comfortable addressing the questions asked or topics the video chat requestor would like to discuss, you can decline the call. You can accept as many or as few video chats as you would like at your discretion. The information on your profile can be edited or updated at any time to highlight your current skills.</p>
               <div class="divider"></div>
<i><strong>What if I can't find a researcher who has the skills I need?</strong></i>
             <p class="profile_text">We are continuously adding new experts/mentors to the site. If you can’t find someone who has the expertise or skills you need, you can <a href="{% url 'booking:request_expert' %}">submit a help request</a>. Our team will find someone with the right expertise, and then you can decide whether you would like to schedule a video session with that mentor.</p>

        
    <div class="divider"></div>
      
       

     
       </div>
    </div>
 
    </div>

    


</div>



    		<footer class="footer-distributed">

			<div class="footer-right">

<!--				<a href="#"><i class="fab fa-facebook-f"></i></a>-->
				<a href="https://twitter.com/scipertise"><i class="fab fa-twitter"></i></a>
				<a href="https://www.linkedin.com/company/scipertise/"><i class="fab fa-linkedin-in"></i></a>
				

			</div>

			<div class="footer-left">

                
                <p class="footer-links">
                    Scipertise &copy; 2018
					<a id="first_link" href="{% url 'home' %}">Home</a>
					·
					<a href="#howitworks">About</a>
					·
					<a href="mailto:founders@scipertise.com">Contact</a>
				</p>
			</div>

		</footer>
   

{% endblock %}

templates/help_form.html
{% extends 'layout.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Sign Up{% endblock %}

{% block content %}


<div class="container-fluid" id="signup">
    <div class="signup_bgrd">
        


 <h3 class="booking_form_text">What do you need help with?</h3>
 {% if form.errors %}
        <br>
<p>There was an error. Please try again.</p>
{% endif %}               
<form method="post">
      {% csrf_token %}

    <div class="form-group">
     {% for field in form.visible_fields %}
     {{ field.errors }}
      {{ field.label_tag }}
      {% render_field field class="form-control" %}
      {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text |safe }}</small>
      {% endif %}
    {% endfor %}
    </div>
  <button type="submit" class="availability_button">Submit</button>
</form>
        
        
        
        
        
<!--
        
            <h4>Sign up for a free account</h4>
         <form class="signup_form" action="" method="POST">
             {% csrf_token %}
             {{ form.as_p }}
                <p class="form_text" label="First Name">First Name:</p>
                 {{ form.first_name }}
                <p class="form_text" label="Last Name">Last Name:</p>
                 {{ form.last_name }}
                <p class="form_text" label="Email">Email:</p>
                 {{ form.email  }}
                <p class="form_text" label="Password">Password:</p>
                 {{ form.password1 }}
                 <br>     
      <button type="submit" class="btn btn-primary">Sign up</button>
               </form>
-->
    </div>


</div>



{% endblock %}

templates/home.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}

        
        <div class="container-fluid" id ="first_section_row">

                <div class="container" id="vision">
                <div class ="container" id="vision_text">
                    <h1 class="value_prop">Find a scientist for live research help</h1>
                    <p class="vision_blurb">Find a scientist who has the right expertise and get live research advice tailored to you.</p>
                    <p class="advice_blurb">Get insights on: <br> experimental models  |  software  |  lab techniques  |  equipment  |   data analysis</p>
                </div>


                </div>
                <div class = "container" id="call_to_action">
                    <form>
                        {% if user.is_authenticated %}
                        <div class="container">
                        <a href="{% url 'browse' %}"><button type="button" class="btn btn-primary" id ="call_to_action">Find Expertise</button></a>
                        <a href="{% url 'edit_profile' %}"><button type="button" class="btn btn-primary" id ="call_to_action">Become an Expert</button></a>
                            </div>
                        {% else %}
                         <div class="container">
                        <a href="{% url 'browse' %}"><button type="button" class="btn btn-primary" id ="call_to_action">Find Expertise</button></a>
                        <a href="{% url 'signup' %}"><button type="button" class="btn btn-primary" id ="call_to_action">Become an Expert</button></a>
                               </div>
                        {% endif %}
                     
                    </form>
                </div>

            </div>
                <div class="container-fluid" id="second_section_row">

                <a name="howitworks"></a> 
                 <div class="divtitle">
                    <h1>How it works</h1>
                     
 
                </div>
               <div class="container-fluid" id="howitworks">
                <div class="container" id="step1" >
                
                
                    <img class="icon1" src="/static/css/scipertise_icon_step1.png">
                     
                        <h4 class ="icon_title">Find a Scientist</h4>
                        <p class="icontext">Browse researcher profiles or search for an expert by skill. Message someone to see if they're the right fit.</p>
               
                      
                </div>
                
                <div class="container" id="step2" >
                  
                    <img class="icon2" src="/static/css/scipertise_icon_step2.png">
                     
                        <h4 class ="icon_title">Book a Call</h4>
                        <p class="icontext">Schedule a video call with an expert of your choice. Get quick advice, help troubleshooting, or book a tutorial.</p>   
                </div>
                
                <div class="container" id="step3" >
                
                    <img class="icon3" src="/static/css/scipertise_icon_step3.png">
                        <h4 class ="icon_title">Solve Problems</h4>
                        <p class="icontext">Discuss, learn and solve problems with someone who has the right expertise. Move your research forward.</p>
                 
                    
                    
                </div>

            </div>
         </div>

        <div class="container-fluid" id="web_section_row">
        <div class="web_demo_row">
            <div class="container web_demo_text">
                <h2 class="bio_title">Browse Researchers by Skill</h2>
                <p class="profile_text">Find someone who has the right skills</p>
                <p class="profile_text">Personalize your learning</p>
                <p class="profile_text">Can't find what you're looking for?</p><p class="profile_text"><a href="{% url 'booking:request_expert' %}">Submit a request</a> and we'll find the right person</p><br><br>
              <a href="{% url 'browse' %}"><button type="button" class="btn btn-primary" id ="call_to_action">Find Expertise</button></a>
            </div>
            <div class="container">
                <img class="web_demo" src="/static/css/website_graphics.png">
            
            </div>
            </div>
            
             </div>



    <div class="container-fluid" id="web_section_row">
        <div class="web_demo_row">
        <div class="container">
                <img class="web_demo_2" src="/static/css/website_graphics_2.png">
            
            </div>
            <div class="container web_demo_text">
                <h2 class="bio_title">Get Live 1:1 Research Help</h2>
                <p class="profile_text">Message a researcher to see if they can help</p>
                <p class="profile_text">Get research advice tailored to your needs</p>
                <p class="profile_text">Troubleshoot or learn a new research technique</p><br><br>
                 <a href="{% url 'browse' %}"><button type="button" class="btn btn-primary" id ="call_to_action">Find Expertise</button></a>
            
            </div>
         
            </div>
            
             </div>


      






            
               
        <div class="container-fluid" id ="third_section_row">
            <div class="container" id="section3_signup" > 
                <h2 class="section3_text">Scipertise is a marketplace for on-demand scientific expertise. Join the movement and do better research, faster.</h2>
            <a href="{% url 'signup' %}"><button type="button" class="btn btn-primary" id ="call_to_action">Sign up for beta access</button></a>
           
            </div>

          
</div>

    		<footer class="footer-distributed">

			<div class="footer-right">

				<a href="https://twitter.com/scipertise"><i class="fab fa-twitter"></i></a>
				<a href="https://www.linkedin.com/company/scipertise/"><i class="fab fa-linkedin-in"></i></a>
				

			</div>

			<div class="footer-left">

                
                <p class="footer-links">
                    Scipertise &copy; 2018
					<a id="first_link" href="{% url 'home' %}">Home</a>
					·
					<a href="{% url 'faq' %}">About</a>
					·
					<a href="mailto:founders@scipertise.com">Contact</a>
				</p>
			</div>

		</footer>
   

{% endblock %}

templates/layout.html
{% load static %}
{% load bootstrap4 %}       {# imports bootstrap3 #}
{% bootstrap_css %}         {# Embeds Bootstrap CSS #}
{% bootstrap_javascript %}
{% bootstrap_javascript jquery='full' %} {# Embeds Bootstrap JS #}
{% block extrahead %} 
 {{ form.media }}          {# Embeds Extra Resources #}
{% endblock %}              {# Ends Extra Resources #}

<!doctype html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
  
    <link href="https://fonts.googleapis.com/css?family=Montserrat|PT+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel='shortcut icon' type='image/x-icon' href='/static/css/favicon.ico' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Scipertise">
    <meta name="twitter:image" content="/static/css/brand.jpg">
    <meta name="twitter:description" content="Scipertise is a platform for finding live scientific research help and tutorials">

<!--
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
-->

<!--    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
     <!-- Hotjar Tracking Code for scipertise.com -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:1210885,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
    </head>
<body>  

<div class ="site-container">
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <a class="navbar-left logo" href="{% url 'home' %}"><img class="logo" src="/static/css/brand.jpg"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button> 
          <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
               
            <div class="navbar-nav">
                 <!-- <a class="nav-item nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a> -->
              
                {% if user.is_authenticated %}
                
                <form class="form-inline my-2 my-lg-0" action="{% url 'search:search_users' %}" method="GET" value="{{request.GET.q}}">
                  <input class="form-control mr-sm-2" type="text" name="q" value="{{request.GET.q}}" placeholder="Search by Skill">
                  <button class="btn btn-primary my-2 my-sm-0" id = "search" name="submit" type="submit" value ="Search">Search</button>
                </form>
                
    <div class="dropdown show">
    <a class="btn btn-primary dropdown-toggle" href="{% url 'browse' %}" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Find Expertise
  </a>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'browse' %}">Browse Researchers</a>
                    <a class="dropdown-item" href="{% url 'booking:request_expert' %}">Request Help</a>
                    <a class="dropdown-item" href="{% url 'booking:tutorial_list' %}">Find a Tutorial</a>
                  </div>
                </div>
                
                
<!--                <a class="nav-item nav-link" href="{% url 'booking:tutorial_list' %}">Tutorials</a>-->
                <a class="nav-item nav-link" href="{% url 'faq' %}">FAQ</a>
                  <a class="nav-item nav-link" href="{% url 'profile' %}">My Profile</a>
                  <a class="nav-item nav-link" href="{% url 'booking:booking_list' %}"> My Schedule</a>
                  <a class ="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                
            {% else %}
    <div class="dropdown show">
        <a class="btn btn-primary dropdown-toggle" href="{% url 'browse' %}" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Find Expertise
      </a>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'browse' %}">Browse Researchers</a>
                        <a class="dropdown-item" href="{% url 'booking:request_expert' %}">Request Help</a>
        </div>
                </div>

                
                  <a class="nav-item nav-link" href="{% url 'faq' %}">FAQ</a>
                  <a class ="nav-item nav-link" id="login" href="{% url 'login' %}">Login</a>
<!--
                <form class="form-inline my-2 my-lg-0">
                    <a  href="{% url 'signup' %}"><button class="btn btn-primary" type="button">Sign Up</button></a>
                  </form>
-->
                <a class ="nav-item nav-link" href="{% url 'signup' %}">Sign Up</a>
                {% endif %}
                
            </div>
          </div>
    </nav>

        
  <!--  {% if messages %}
       <div class ="row">
       {% for message in messages %}
           <div data-alert class="alert-box {{ message.tags }} radius"></div>
            {{ message }}
           <a href="#" class ="close">&times;</a>
       </div>
       {% endfor %}
       {% endif %} -->
        
        
    {% block content %}{% endblock %}
    </div> 
    

    </body>